version: '3'
services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile-Monitor
    restart: unless-stopped
  query:
    build:
      context: .
      dockerfile: Dockerfile-Query
    restart: unless-stopped
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

volumes:
  mongodb-data: